api:
  dashboard: true
  insecure: true

log:
  level: INFO

providers:
  docker:
    network: traefik-public
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@agentic.hosting
      storage: /etc/traefik/certs/acme.json
      httpChallenge:
        entryPoint: web
