FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /usr/share/nginx/html/index.html
COPY install.sh /usr/share/nginx/html/install.sh
COPY changelog /usr/share/nginx/html/changelog
COPY dashboard /usr/share/nginx/html/dashboard
COPY install-skill.sh /usr/share/nginx/html/install-skill.sh
